### ISSUE TITLE
Notes lose location highlight

### ISSUE THREAD

**Issue by ivanbranco** [deevroman/better-osm-org#11]
Hi, I noticed that while using the script (left image, right image is behaviour without script on), notes lose the "orange-circle-location-thing". This can be confusing when there are more notes clustered in the same area. Is this intended or a bug?
![photo_2024-05-07_11-09-36](https://github.com/deevroman/better-osm-org/assets/94002623/419c4e51-b5b2-4d57-830b-1d1f5639fffc)

**Comment by deevroman** [comment]
This is by design, but you can turn it off in the settings.


<img width="428" alt="Снимок экрана 2024-05-07 в 12 24 03" src="https://github.com/deevroman/better-osm-org/assets/25708359/052532a4-64b1-4b05-8987-935db9d5b003">


The idea is that when you turn on a data layer, the highlight makes it difficult to highlight the point it belongs to. But I clearly need to teach the script to make the current note marker more visible.

**Comment by ivanbranco** [comment]
Oh ok, if is by design it can be closed I guess. By the way thanks for the script, now that I have this history viewer I wonder why is not a core feature of the website!

**Comment by deevroman** [comment]
Note markers on osm.org will soon https://github.com/openstreetmap/openstreetmap-website/commit/b2fcf003f8e5c928cabf36ae9a01ef393de8874f become svg images, making them easy to change to make the current note marker more visible.  So I'll keep this open for the future.

**Comment by deevroman** [comment]
In 0.4, the highlight is removed only if the Map Data layer is enabled.  This also changes the color of the note slightly.
