### ISSUE TITLE
Stat HDYC in profile (Chrome sometimes)

### ISSUE THREAD

**Issue by ivanbranco** [deevroman/better-osm-org#15]
The README says: _Stat HDYC in profile (Firefox only)_

This is true most of the time, I have Chrome and I can't read the stats...but! Sometimes it happens I find users of whose the stats are visible, example: 
![image](https://github.com/deevroman/better-osm-org/assets/94002623/8761c4c3-e0fb-4517-84b6-f12f8d38ef1c)

maybe this could help you understand what the problem is?

**Comment by deevroman** [comment]
HDYC by default requires authorization to view the user's profile.  But if the user has made the profile public ([green checkmark](https://shtosm.ru/all/vozhdelennaya-galochka/)), then authorization is not needed.

The problem is that I embed the HDYC site into the OSM site and Chrome blocks the cookies that are responsible for authorization, and HDYC stops showing the profile of non-public users.

**Comment by ForgottenHero** [comment]
Hey @deevroman, so when I'm looking at other people's user profiles I nearly always see the error "**Please disable tracking protection so that the HDYC account login works**". I made sure I'm logged in to HDYC.

Is this for me to turn off some sort of tracking protection? Or is it saying the user I'm viewing would need to change their profile settings for their HDYC to display?
Here's a random user I was checking today:
![image](https://github.com/deevroman/better-osm-org/assets/4233945/8b10e381-ee30-4da6-a04b-315884b01c0a)

**Comment by deevroman** [comment]
@ForgottenHero In the case of Firefox we are talking about this: https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop#w_how-to-tell-when-firefox-is-protecting-you

If you are using Chrome, then unfortunately this feature will only work for public HDYC profiles.  You can click on the Tampermonkey icon->Settings->Other and disable this feature

**Comment by deevroman** [comment]
Good and bad news.

Good, there is a way to force HDYC to be selected. The bad news is that you have to do it manually:

1. Log in to HDYC
2. Open the browser console (F12)
3. Open the Application tab
4. In the left panel, select Storage→Cookies→https://www.hdyc.neis-one.org
5. Click on the cell with the name SameSite and type None in it

![изображение](https://github.com/user-attachments/assets/6877ae92-cbcc-4784-9c16-aa47ba88d276)

I will add this instruction to the next version of the script
